name: application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_riverpod: ^2.4.9
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  go_router: ^13.0.0
  hooks_riverpod: ^2.4.9
  http: ^1.1.2
  json_annotation: ^4.8.1
  mockito: ^5.4.4
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  go_router_builder: ^2.4.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
