name: Build application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: application/
jobs:
  build:
    name: "Build iOS/Android"
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.5"
      - name: Install Dependency
        run: flutter pub get
      - name: Build iOS App
        run: flutter build ios --simulator
      - name: Build Android App
        run: flutter build appbundle --debug
      - name: Run Tests
        run: flutter test
